# Generated by Django 3.2.6 on 2021-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageUrl',
            field=models.URLField(default='https://lh3.googleusercontent.com/proxy/srsv7ttgYG8RW-2SOQLH3NfJrIj7EwaYMZmi9V1Zk4Ug5y5Aq3F2_S4azDIbTxE9cqhtlrtFtwsP2KOpLbjOL--Q2JpXzP1pLZ0-1tyH7pARkXhPv4reFJEQQLcHuhRDIeCQSg'),
        ),
    ]
