# Generated by Django 3.2.6 on 2021-08-07 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('MercedesBenz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Tesla', 'Tesla'), ('Porsche', 'Porsche'), ('Lexus', 'Lexus'), ('Volvo', 'Volvo'), ('Lamborghini', 'Lamborghini'), ('Ferrari', 'Ferrari'), ('LandRover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Cadillac', 'Cadillac'), ('RollsRoyce', 'Rolls-Royce'), ('Maserati', 'Maserati'), ('Bugatti', 'Bugatti')], max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
