# Generated by Django 3.2.6 on 2021-08-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210808_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['price']},
        ),
    ]
